export const dataTabs = [
  {
    name: "Domains",
    content: [
      { title: ".COM", firstPrice: "$5.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".Al", firstPrice: "$55.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".NET", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".HEALTH", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO.UK", firstPrice: "$3.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".ORG", firstPrice: "$15.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".SEA", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
    ],
  },
  {
    name: "Web Hosting",
    content: [
      { title: ".CO", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".NET", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".COM", firstPrice: "$5.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".Al", firstPrice: "$55.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".SEA", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".HEALTH", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".ORG", firstPrice: "$15.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO.UK", firstPrice: "$3.99/yr", secondPrice: "Instead of $10.99 yr" },
    ],
  },
  {
    name: "Dedicated Servers",
    content: [
      { title: ".HEALTH", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO.UK", firstPrice: "$3.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".ORG", firstPrice: "$15.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".COM", firstPrice: "$5.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".Al", firstPrice: "$55.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".SEA", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".NET", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
    ],
  },
  {
    name: "Virtual Cloud Servers",
    content: [
      { title: ".NET", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".HEALTH", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO.UK", firstPrice: "$3.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".COM", firstPrice: "$5.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".SEA", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".Al", firstPrice: "$55.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".ORG", firstPrice: "$15.99/yr", secondPrice: "Instead of $10.99 yr" },
    ],
  },
  {
    name: "WordPress Hosting",
    content: [
      { title: ".CO.UK", firstPrice: "$3.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".ORG", firstPrice: "$15.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".NET", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".SEA", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".HEALTH", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".Al", firstPrice: "$55.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".COM", firstPrice: "$5.99/yr", secondPrice: "Instead of $10.99 yr" },
    ],
  },
  {
    name: "Email Hosting",
    content: [
      { title: ".ORG", firstPrice: "$15.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".HEALTH", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".COM", firstPrice: "$5.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO.UK", firstPrice: "$3.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".Al", firstPrice: "$55.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".SEA", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".NET", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
    ],
  },
  {
    name: "VPS Hosting Servers",
    content: [
      { title: ".Al", firstPrice: "$55.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".NET", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".HEALTH", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".SEA", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO.UK", firstPrice: "$3.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".ORG", firstPrice: "$15.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".COM", firstPrice: "$5.99/yr", secondPrice: "Instead of $10.99 yr" },
    ],
  },
  {
    name: "Free Hosting",
    content: [
      { title: ".CO", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".NET", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".SEA", firstPrice: "$26.33/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".ORG", firstPrice: "$15.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".COM", firstPrice: "$5.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".CO.UK", firstPrice: "$3.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".Al", firstPrice: "$55.99/yr", secondPrice: "Instead of $10.99 yr" },
      { title: ".HEALTH", firstPrice: "$7.99/yr", secondPrice: "Instead of $10.99 yr" },
    ],
  },
];
